### ISSUE TITLE
Style leads to blank printing

### ISSUE THREAD

**Issue by qjebbs** [microsoft/vscode-docs-authoring#322]
In `site-ltr.css`:

```css
@media print {
  ...
  body > :not(.mainContainer),
  ...,
  ..., {
    display: none !important;
}
```

Any page includes this style, will print nothing, including PDF exporting, which is reported by my user here: https://github.com/qjebbs/vscode-markdown-extended/issues/56

BTW: I suggest assign style with `body.vscode-body` instead of `body.mainContainer`, to make it consistent with vscode markdown engine.
