### ISSUE TITLE
Provide warnings for toc.yml files where displayName nodes are invalid 

### ISSUE THREAD

**Issue by IEvangelist** [microsoft/vscode-docs-authoring#767]
Suggestion, provide warnings for _toc.yml_ files where `displayName` nodes are invalid:

In *toc.yml* files, if a `displayName` node exists where the node it is decorating only contains `items`, the `displayName` is not 
actually used. In other words, the `displayName` is only valid on nodes that have an `href`.

#### Example

These are two examples of valid `displayName` nodes.

```yml
- name: Top level section
  items:
  - name: Overview
    displayName: values,in the,display name here, are actually, valid,since they are directly,tied to an,href
    href: overview.md
  - name: Secondary node
    items:
    - name: Overview
      displayName: these,values,are,valid too
      href: ../core/sdk.md
    - name: Some section
      items:
      - name: Another file
        href: ../core/tools/dir/another--file.md
      - name: Some file
        href: ../core/tools/dir/some-file.md
```

However, if someone was to add a `displayName` to the "Top level section" we should warn the author that their `displayName` is invalid, and will have no effect. It is completely useless.

```yml
- name: Top level section
  displayName: this,is pointless,warn me about, it please # This will not work, no HREF
  items:
  - name: Overview
    displayName: values,in the,display name here, are actually, valid,since they are directly,tied to an,href
    href: overview.md
  - name: Secondary node
    items:
    - name: Overview
      displayName: these,values,are,valid too
      href: ../core/sdk.md
    - name: Some section
      items:
      - name: Another file
        href: ../core/tools/dir/another--file.md
      - name: Some file
        href: ../core/tools/dir/some-file.md
```

[AB#325494](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/325494)
