### ISSUE TITLE
Property ${{ each env in parameters.environments }} is not allowed

### ISSUE THREAD

**Issue by ikivanc** [microsoft/vscode-docs-authoring#828]
Hi Team,

I wanted to validate my YAML for Azure Pipelines, I have an environment iteration using `each` loop and it's working fine in my pipeline. However with [docs-yaml](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-yaml&ssr=false#overview) extension, I do retrieve below error for linting:

> Property ${{ each env in parameters.environments }} is not allowed.yaml-schema: Pipeline schema

Is it possible to add a validation for each loops?

Here's my pipeline to use this iteration:

```yaml
trigger:
- master

parameters:
- name: environments
  type: object
  default: ['dev','qa', 'prd']

variables:
- template: vars/vars-global.yml

stages:
- stage: build
  jobs:
    - job: build
      steps:
        - template: azure-build.yaml
- ${{ each env in parameters.environments }}:
  - stage: test_${{ env }}
    jobs:
      - job: run_test
        variables:          
        - template: vars/vars-${{ env }}.yml
        steps:
          - template: steps-tests.yaml
  - stage: deploy_${{ env }}
    variables:          
      - template: vars/vars-${{ env }}.yml
    jobs:
    - deployment: DeploymentJob
      pool:
        vmImage: ${{ variables.vmImageName }}
      environment: ${{ variables.environmentName }}
      strategy:
        runOnce:
          deploy:
            steps:
              - template: steps-deployment.yaml
                parameters:
                  azureServiceConnectionId: ${{ variables.azureServiceConnectionId  }}
                  webAppName: ${{ variables.webAppName  }}
```

Thanks
