### ISSUE TITLE
[BUG]: workflow for Azure migration for issues is broken

### ISSUE THREAD

**Issue by Falcion** [microsoft/vscode-docs-authoring#963]
Workflow on this repository throws an error for user which opened the issue (not maintainer or contributor):

![Image](https://github.com/user-attachments/assets/7341ce2f-ac7c-49a4-b82f-e43b14675874)

Current version of the workflow is `v1.5`: at the moment of the opening this issue, version `v2.4` is released. I tried to adapt current workflow (I will open PR later) to newer versions:

```yaml
name: Sync issue to Azure DevOps work item

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  sync_to_azure:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitHub Issue to Azure DevOps Work Item
        uses: danhellem/github-actions-issue-to-work-item@v2.4
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "ceapex"
          ado_project: "Engineering"
          ado_area_path: "Engineering\\Authoring"
          # Optional, added for better tracking
          # ado_iteration_path: "Engineering\\Iteration1"  
          ado_wit: "User Story"
          ado_new_state: "New"
          # Required for work items that need an intermediate state
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100  # Enables detailed logging for debugging
```
